"""Tests for core agent functionality."""

import json

import pytest
from unittest.mock import MagicMock

from web3_agent_kit.agent.core import Agent, AgentConfig
from web3_agent_kit.wallet.wallet import Wallet
from web3_agent_kit.chains.chain import Chain


class TestWallet:
    """Test wallet creation and management."""

    def test_from_key(self):
        """Test wallet creation from private key."""
        # This is a test key, never use in production
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)
        assert wallet.address.startswith("0x")
        assert len(wallet.address) == 42

    def test_from_env_missing(self, monkeypatch):
        """Test wallet creation from missing env var."""
        monkeypatch.delenv("PRIVATE_KEY", raising=False)
        with pytest.raises(ValueError, match="not set"):
            Wallet.from_env("PRIVATE_KEY")

    def test_from_env(self, monkeypatch):
        """Test wallet creation from env var."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        monkeypatch.setenv("TEST_KEY", key)
        wallet = Wallet.from_env("TEST_KEY")
        assert wallet.address.startswith("0x")

    def test_from_keystore(self, tmp_path):
        """Test wallet creation from a standard Ethereum JSON keystore file."""
        from eth_account import Account

        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        expected_address = Account.from_key(key).address

        # Use low iteration count purely to keep the test fast; production
        # keystores generated by wallets/clients use much higher work factors.
        keystore_json = Account.encrypt(
            key, password="test-password-123", kdf="pbkdf2", iterations=1000
        )
        keystore_path = tmp_path / "keystore.json"
        keystore_path.write_text(json.dumps(keystore_json))

        wallet = Wallet.from_keystore(str(keystore_path), password="test-password-123")

        assert wallet.address == expected_address
        assert wallet.config.keystore_path == str(keystore_path)

    def test_from_keystore_wrong_password(self, tmp_path):
        """Wrong password against a keystore must raise, not silently decrypt garbage."""
        from eth_account import Account

        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        keystore_json = Account.encrypt(
            key, password="correct-password", kdf="pbkdf2", iterations=1000
        )
        keystore_path = tmp_path / "keystore.json"
        keystore_path.write_text(json.dumps(keystore_json))

        with pytest.raises(ValueError):
            Wallet.from_keystore(str(keystore_path), password="wrong-password")

    def test_from_keystore_missing_file(self, tmp_path):
        """Missing keystore file must raise FileNotFoundError."""
        missing_path = tmp_path / "nonexistent-keystore.json"
        with pytest.raises(FileNotFoundError):
            Wallet.from_keystore(str(missing_path), password="anything")


class TestChain:
    """Test chain configuration."""

    def test_chain_enum(self):
        """Test chain enum values."""
        assert Chain.ETHEREUM.value == "ethereum"
        assert Chain.BASE.value == "base"
        assert Chain.SOLANA.value == "solana"

    def test_chain_config(self):
        """Test chain configuration."""
        from web3_agent_kit.chains.chain import ChainConfig
        config = ChainConfig(chain=Chain.BASE)
        assert config.is_evm is True
        assert config.chain_id == 8453
        assert "base" in config.explorer.lower()

    def test_solana_not_evm(self):
        """Test Solana is not EVM."""
        from web3_agent_kit.chains.chain import ChainConfig
        config = ChainConfig(chain=Chain.SOLANA)
        assert config.is_evm is False


class TestGovernor:
    """Test spend governor."""

    def test_within_limits(self):
        """Test transaction within limits."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        governor = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0, daily_limit=10.0),
            require_confirm=False,
        )
        decision = governor.authorize(0.5)
        assert decision.allowed is True

    def test_exceeds_per_tx(self):
        """Test transaction exceeds per-tx limit."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        governor = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0),
            require_confirm=False,
        )
        decision = governor.authorize(2.0)
        assert decision.allowed is False
        assert "per-tx limit" in decision.reason

    def test_kill_switch(self):
        """Test kill switch blocks transactions."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        governor = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0),
            require_confirm=False,
        )
        governor.kill()
        decision = governor.authorize(0.1)
        assert decision.allowed is False
        assert "Kill switch" in decision.reason

    def test_daily_limit(self):
        """Test daily spending limit."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        governor = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0, daily_limit=2.0),
            require_confirm=False,
        )
        # First transaction
        assert governor.authorize(1.0).allowed is True
        # Second transaction
        assert governor.authorize(1.0).allowed is True
        # Third transaction (exceeds daily)
        assert governor.authorize(1.0).allowed is False


class TestAgentGovernorIntegration:
    """Integration test: Agent._act() must actually call the governor
    correctly (tx_value as float, action as tool name string) and must
    block over-limit actions gracefully instead of crashing with a
    TypeError (regression test for the dict-vs-float bug)."""

    def _make_agent(self, governor):
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)

        mock_tool = MagicMock()
        mock_tool.name = "swap"
        mock_tool.execute.return_value = "swapped ok"

        config = AgentConfig(
            wallet=wallet,
            chains=[Chain.ETHEREUM],
            tools=[mock_tool],
            governor=governor,
        )
        return Agent(config=config), mock_tool

    def test_act_blocks_over_limit_tx_without_crashing(self):
        """A tool call whose args imply a tx value above the governor's
        per-tx limit must be blocked with a clean message, not raise."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits

        governor = SpendGovernor(
            SpendLimits(max_per_tx=0.05, daily_limit=0.5, session_limit=1.0),
            require_confirm=False,
        )
        agent, mock_tool = self._make_agent(governor)

        result = agent._act({"tool": "swap", "args": {"amount": 1.0}})

        assert result.startswith("Blocked by governor:")
        mock_tool.execute.assert_not_called()

    def test_act_allows_under_limit_tx(self):
        """A tool call under the governor's limits must pass through and
        actually execute the tool."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits

        governor = SpendGovernor(
            SpendLimits(max_per_tx=0.05, daily_limit=0.5, session_limit=1.0),
            require_confirm=False,
        )
        agent, mock_tool = self._make_agent(governor)

        result = agent._act({"tool": "swap", "args": {"amount": 0.01}})

        assert result == "swapped ok"
        mock_tool.execute.assert_called_once()

    def test_act_blocks_action_with_unknown_value(self):
        """Tools with no recognizable value arg must be blocked
        (tx_value is None, not 0.0)."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits

        governor = SpendGovernor(
            SpendLimits(max_per_tx=0.05, daily_limit=0.5, session_limit=1.0),
            require_confirm=False,
        )
        agent, mock_tool = self._make_agent(governor)

        result = agent._act({"tool": "swap", "args": {"address": "0xabc"}})

        assert "blocked" in result.lower() or "unknown" in result.lower()
        mock_tool.execute.assert_not_called()

    def test_agent_config_has_default_governor(self):
        """AgentConfig must attach a conservative governor by default so
        agents never run with unbounded spending out of the box."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)
        config = AgentConfig(wallet=wallet)

        assert config.governor is not None
        assert config.governor.limits.max_per_tx == 0.05
        assert config.governor.limits.daily_limit == 0.5
        assert config.governor.limits.session_limit == 1.0


class TestSpendGovernorIntegration:
    """Tests for SpendGovernor interaction with Agent."""

    def test_require_confirm_without_fn_raises(self):
        """require_confirm=True without confirm_fn must raise ValueError."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits

        with pytest.raises(ValueError, match="require_confirm=True requires a confirm_fn"):
            SpendGovernor(
                limits=SpendLimits(max_per_tx=0.01),
                require_confirm=True,
                confirm_fn=None,
            )

    def test_require_confirm_false_allows_none_fn(self):
        """require_confirm=False should not require confirm_fn."""
        from web3_agent_kit.utils import SpendGovernor, SpendLimits

        gov = SpendGovernor(
            limits=SpendLimits(max_per_tx=0.01),
            require_confirm=False,
            confirm_fn=None,
        )
        assert gov.confirm_fn is None

    def test_confirm_fn_wired_from_config_to_governor(self):
        """confirm_fn set on AgentConfig must be wired to the governor."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)
        confirm_called = False

        def my_confirm(payload):
            nonlocal confirm_called
            confirm_called = True
            return True

        config = AgentConfig(
            wallet=wallet,
            governor=None,  # no auto governor—we'll create our own
        )
        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        config.governor = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0),
            require_confirm=True,
            confirm_fn=my_confirm,
        )

        agent = Agent(config=config)
        assert agent.config.governor.confirm_fn is my_confirm

    def test_confirm_fn_called_during_act(self):
        """confirm_fn must be invoked when agent executes a tool action."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)
        confirm_payload = []

        def my_confirm(payload):
            confirm_payload.append(payload)
            return True

        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        gov = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0, daily_limit=10.0, session_limit=50.0),
            require_confirm=True,
            confirm_fn=my_confirm,
        )

        mock_tool = MagicMock()
        mock_tool.name = "swap"
        mock_tool.supported_chains = [Chain.ETHEREUM]
        mock_tool.execute.return_value = "swapped ok"

        config = AgentConfig(wallet=wallet, governor=gov, tools=[mock_tool])
        agent = Agent(config=config)

        result = agent._act({"tool": "swap", "args": {"amount": 0.1, "address": "0xabc"}})

        assert confirm_payload, "confirm_fn was never called"
        assert confirm_payload[0]["action"] == "swap"
        assert confirm_payload[0]["value"] == 0.1
        assert "swapped ok" in result

    def test_confirm_fn_rejects_blocks_action(self):
        """When confirm_fn returns False, the action must be blocked."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)

        def rejecting_confirm(payload):
            return False

        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        gov = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0),
            require_confirm=True,
            confirm_fn=rejecting_confirm,
        )

        mock_tool = MagicMock()
        mock_tool.name = "swap"
        mock_tool.supported_chains = [Chain.ETHEREUM]
        mock_tool.execute.return_value = "should not be called"

        config = AgentConfig(wallet=wallet, governor=gov, tools=[mock_tool])
        agent = Agent(config=config)

        result = agent._act({"tool": "swap", "args": {"amount": 0.1}})
        assert "rejected" in result.lower() or "blocked" in result.lower()
        mock_tool.execute.assert_not_called()

    def test_estimate_tx_value_unknown_key_returns_none(self):
        """Keys not in the recognised list must return None, not 0.0."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)
        config = AgentConfig(wallet=wallet, governor=None)
        agent = Agent(config=config)

        value = agent._estimate_tx_value({"some_random_key": 100})
        assert value is None, f"Expected None, got {value}"

    def test_unknown_tx_value_blocked_by_governor(self):
        """When tx_value is None (unknown), _act must block."""
        key = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
        wallet = Wallet.from_key(key)

        from web3_agent_kit.utils import SpendGovernor, SpendLimits
        gov = SpendGovernor(
            limits=SpendLimits(max_per_tx=1.0),
            require_confirm=False,
        )

        mock_tool = MagicMock()
        mock_tool.name = "swap"
        mock_tool.supported_chains = [Chain.ETHEREUM]
        mock_tool.execute.return_value = "should not execute"

        config = AgentConfig(wallet=wallet, governor=gov, tools=[mock_tool])
        agent = Agent(config=config)

        result = agent._act({"tool": "swap", "args": {"unknown_key": 99}})
        assert "blocked" in result.lower() or "unknown" in result.lower()
        mock_tool.execute.assert_not_called()


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
